### PR TITLE
Update operation.go - fix typo

### PR DESCRIPTION
**Pull request by ianb-mp**
Fix typo in log message.

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by niladrih — APPROVED** [review]
LGTM!

**Comment by ianb-mp** [comment]
@Abhinandan-Purkait fyi

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by ianb-mp** [comment]
Is there any reason not to merge this PR?

**Review by avishnu — APPROVED** [review]

**Comment by avishnu** [comment]
> Is there any reason not to merge this PR?

Some CI test is not getting executed. Merging the PR, as the issue is unrelated.

**Pull request merged**
